name: EmptySwiftUIProject
options:
  bundleIdPrefix: com.your.organization
  deploymentTarget:
    iOS: 15.0

settings:
  base:
    DEVELOPMENT_TEAM: "" # 在这里填入你的开发者团队 ID

targets:
  EmptySwiftUIProject:
    type: application
    platform: iOS
    sources:
      - EmptySwiftUIProject
    settings:
      base:
        INFOPLIST_FILE: EmptySwiftUIProject/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.your.organization.EmptySwiftUIProject
    
    # 添加CocoaPods支持
    dependencies:
      - sdk: UIKit.framework
      - sdk: SwiftUI.framework

# 添加CocoaPods配置
projectReferences:
  - path: Pods/Pods.xcodeproj

schemes:
  EmptySwiftUIProject:
    build:
      targets:
        EmptySwiftUIProject: all