name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15.3
      
    - name: Install CocoaPods
      run: |
        gem install cocoapods
    
    - name: Run SwiftLint
      run: make fix
    
    - name: Run generate
      run: make gen
    
    - name: Build
      run: |
        xcodebuild clean build -workspace EmptySwiftUIProject.xcworkspace -scheme EmptySwiftUIProject -destination 'platform=iOS Simulator,name=iPhone 14'
        
    - name: Run tests
      run: |
        xcodebuild test -workspace EmptySwiftUIProject.xcworkspace -scheme EmptySwiftUIProject -destination 'platform=iOS Simulator,name=iPhone 14'
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3